const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const parser=require('../manual-data');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage();await page.goto('http://127.0.0.1:4001');
 await page.locator('#importText').fill('Rank\tTeam\tRating\n1\tPittsburgh Stars 14U AAA (PA)\t92.69');await page.locator('#previewImport').click();await page.locator('#confirmSeason').check();await page.locator('#applyImport').click();
 const picker=page.getByRole('combobox').first();await picker.fill('pitsburgh stars');await picker.press('ArrowDown');await picker.press('Enter');assert.equal(await page.locator('[data-role=baselineTeam]').inputValue(),'manual:pittsburgh%20stars%2014u%20aaa%20(pa)');
 const context=await browser.newContext();await context.route('https://myhockeyrankings.com/**',route=>route.fulfill({contentType:'text/html',body:route.request().url().includes('/math')?'<table><tr><th>GD</th><th>Opp Rating</th></tr><tr><td>Totals (for rankable games)</td><td>5 - 5 - 2</td><td>42 - 36</td><td>6</td><td>1115.19</td><td>1121.19</td><td>-0.02</td></tr></table>':'<table><tr><th>Rank</th><th>Team</th><th>Rating</th></tr><tr><td>34</td><td><a href="/team-info/123/2026">Pittsburgh Stars 14U AAA (PA)</a></td><td>92.69</td></tr><tr><td>201</td><td><a href="/team-info/999/2026">Excluded team</a></td><td>70</td></tr></table>'}));
 const mhr=await context.newPage();await mhr.goto('https://myhockeyrankings.com/rank.php?y=2026&v=114');await mhr.evaluate('(()=>{'+fs.readFileSync('batch-collector.js','utf8')+';collectBatch()})()');await mhr.getByText('Start / resume',{exact:true}).click();await mhr.getByText('1 / 200 Math pages collected. 1 teams loaded. More ranking rows needed.',{exact:false}).waitFor();
 const job=await mhr.evaluate(()=>sessionStorage.getItem('mhr-calculator-batch-2026-114'));const result=parser.parse(job);assert.equal(result.teams[0].totalGames,12);assert.equal(result.teams[0].totalGoalDifferential,6);assert.equal(result.teams[0].totalOpponentRating,1115.19);assert.equal(result.teams[0].rating,92.69);
 await mhr.reload();await mhr.evaluate('(()=>{'+fs.readFileSync('batch-collector.js','utf8')+';collectBatch()})()');assert.match(await mhr.locator('#mhr-collection-panel').innerText(),/1 \/ 200/);
 console.log('PASS: fuzzy keyboard selection, regular-tab batch collection, exact totals, saved progress restore');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
